---
services:
  sdk:
    user: ${UID}:${GID}
    image: linux-sdk
    build:
      context: .
      dockerfile: ./docker/sdk.Dockerfile
      secrets:
        - netrc
        - gitconfig
    environment:
      HOME: ${PWD}/.home
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true
      - type: bind
        source: /etc/shadow
        target: /etc/shadow
        read_only: true
      - type: bind
        source: ${HOME}/.netrc
        target: ${PWD}/.home/.netrc
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${HOME}/.gitconfig
        target: ${PWD}/.home/.gitconfig
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${PWD}
        target: ${PWD}
    hostname: linux-sdk
    working_dir: ${PWD}
    init: true
    tty: true
    stdin_open: true

  utility:
    user: ${UID}:${GID}
    image: utility
    build:
      context: .
      dockerfile: ./docker/utility.Dockerfile
      secrets:
        - netrc
        - gitconfig
    environment:
      HOME: ${PWD}/.home
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true
      - type: bind
        source: /etc/shadow
        target: /etc/shadow
        read_only: true
      - type: bind
        source: ${HOME}/.netrc
        target: ${PWD}/.home/.netrc
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${HOME}/.gitconfig
        target: ${PWD}/.home/.gitconfig
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ${PWD}
        target: ${PWD}
    hostname: tools
    working_dir: ${PWD}
    init: true
    tty: true
    stdin_open: true

networks:
  sdk-network:
    name: sdk_network
    external: true

secrets:
  netrc:
    file: ${HOME}/.netrc
  gitconfig:
    file: ${HOME}/.gitconfig
